Repository rogemus/BookHub, pull requests merged in 2018-03, with the labels that each got.

#9 Book 9 listing książek front
  BookHub-frontend/src/actions/book.actions.js
  BookHub-frontend/src/actions/books.actions.js
  BookHub-frontend/src/actions/types.js
  BookHub-frontend/src/components/listingItem/listingItem.component.js
  BookHub-frontend/src/containers/bookPage/bookPage.container.js
  BookHub-frontend/src/containers/booksListing/booksListing.container.js
  BookHub-frontend/src/containers/booksListing/booksListing.styles.css
  BookHub-frontend/src/containers/homePage/homePage.container.js
  BookHub-frontend/src/reducers/books.reducer.js
  BookHub-frontend/src/reducers/index.js
Labels: frontend

#6 BOOK-26 | Create Comments App
  .gitignore
  .travis.yml
  BookHub/BookHub/settings/base.py
  BookHub/BookHub/urls.py
  BookHub/books/migrations/0001_initial.py
  BookHub/books/models.py
  BookHub/books/serializers.py
  BookHub/books/tests/book_test_helper.py
  BookHub/books/tests/test_models.py
  BookHub/books/tests/test_views.py
  BookHub/comments/__init__.py
  BookHub/comments/admin.py
  BookHub/comments/apps.py
  BookHub/comments/migrations/0001_initial.py
  BookHub/comments/migrations/__init__.py
  BookHub/comments/models.py
  BookHub/comments/serializers.py
  BookHub/comments/tests/__init__.py
  BookHub/comments/tests/test_views.py
  BookHub/comments/views.py
  BookHub/requirements/base.txt
Labels: backend

#16 add eslint to travice
  .travis.yml
  BookHub-frontend/package.json
Labels: infrastructure

#15 BOOK-12 | Możliwość rejestracji
  BookHub/BookHub/settings/base.py
  BookHub/BookHub/urls.py
  BookHub/users/__init__.py
  BookHub/users/admin.py
  BookHub/users/apps.py
  BookHub/users/migrations/0001_initial.py
  BookHub/users/migrations/0002_auto_20180319_1938.py
  BookHub/users/migrations/__init__.py
  BookHub/users/models.py
  BookHub/users/serializers.py
  BookHub/users/tests/__init__.py
  BookHub/users/tests/test_views.py
  BookHub/users/views.py
Labels: backend

#19 BOOK-15 | BOOK-23 | Add login future (JWT) and improve /comments permissions
  BookHub/BookHub/settings/base.py
  BookHub/BookHub/urls.py
  BookHub/book_hub_auth/__init__.py
  BookHub/book_hub_auth/apps.py
  BookHub/book_hub_auth/migrations/__init__.py
  BookHub/book_hub_auth/urls.py
  BookHub/book_hub_auth/views.py
  BookHub/books/views.py
  BookHub/comments/models.py
  BookHub/comments/permissions.py
  BookHub/comments/tests/comment_test_helper.py
  BookHub/comments/tests/test_models.py
  BookHub/comments/tests/test_views.py
  BookHub/comments/views.py
  BookHub/requirements/base.txt
  tokeny_jwt.txt
Labels: backend

#21 BOOK-40 | Refactor users app and change auth app to accounts
  BookHub/BookHub/settings/base.py
  BookHub/BookHub/urls.py
  BookHub/accounts/__init__.py
  BookHub/accounts/apps.py
  BookHub/accounts/migrations/0001_initial.py
  BookHub/accounts/migrations/__init__.py
  BookHub/accounts/models.py
  BookHub/accounts/permissions.py
  BookHub/accounts/serializers.py
  BookHub/accounts/tests/__init__.py
  BookHub/accounts/tests/test_views.py
  BookHub/accounts/urls.py
  BookHub/accounts/utils.py
  BookHub/accounts/validators.py
  BookHub/accounts/views.py
  BookHub/book_hub_auth/apps.py
  BookHub/book_hub_auth/urls.py
  BookHub/book_hub_auth/views.py
  BookHub/books/apps.py
  BookHub/comments/apps.py
  BookHub/comments/tests/comment_test_helper.py
  BookHub/users/admin.py
  BookHub/users/apps.py
  BookHub/users/forms.py
  BookHub/users/migrations/0001_initial.py
  BookHub/users/migrations/0002_auto_20180319_1938.py
  BookHub/users/models.py
  BookHub/users/serializers.py
  BookHub/users/tests/test_views.py
  BookHub/users/views.py
Labels: backend

#20 BOOK-33 - Connect login form to api
  BookHub-frontend/src/actions/authentication.actions.js
  BookHub-frontend/src/actions/axios.actions.js
  BookHub-frontend/src/actions/types.js
  BookHub-frontend/src/components/loginForm/loginForm.component.js
  BookHub-frontend/src/containers/loginPage/loginPage.container.js
  BookHub-frontend/src/reducers/authentication.reducer.js
  BookHub-frontend/src/reducers/index.js
  BookHub-frontend/webpack.config.js
Labels: frontend

#22 BOOK-47 | Add demo content
  BookHub/db.json
  README.md
Labels: enhancement

#13 Book 13 formularz rejestracyjny
  BookHub-frontend/package-lock.json
  BookHub-frontend/package.json
  BookHub-frontend/src/actions/authentication.actions.js
  BookHub-frontend/src/actions/types.js
  BookHub-frontend/src/components/listingItem/listingItem.component.js
  BookHub-frontend/src/components/registerForm/registerForm.component.js
  BookHub-frontend/src/containers/app.container.js
  BookHub-frontend/src/containers/booksListing/booksListing.styles.css
  BookHub-frontend/src/containers/homePage/homePage.container.js
  BookHub-frontend/src/containers/loginPage/loginPage.container.js
  BookHub-frontend/src/containers/registerPage/registerPage.container.js
  BookHub-frontend/webpack.config.js
Labels: frontend

#23 B33 fix login
  BookHub-frontend/package.json
  BookHub-frontend/src/actions/authentication.actions.js
  BookHub-frontend/src/actions/axios.actions.js
  BookHub-frontend/src/actions/errors.actions.js
  BookHub-frontend/src/actions/types.js
  BookHub-frontend/src/components/errorNotification/errorNotification.component.js
  BookHub-frontend/src/components/errorNotification/errorNotification.styles.css
  BookHub-frontend/src/containers/app.container.js
  BookHub-frontend/src/containers/loginPage/loginPage.container.js
  BookHub-frontend/src/containers/registerPage/registerPage.container.js
  BookHub-frontend/src/reducers/authentication.reducer.js
  BookHub-frontend/src/reducers/errors.reducers.js
  BookHub-frontend/src/reducers/index.js
  BookHub-frontend/src/styles/main.css
Labels: frontend
